import type { Metadata } from 'next';
import { Raleway } from 'next/font/google';
import './globals.css';
import NavBar from '@components/NavBar';

const raleway = Raleway({
    subsets: ['latin'],
    weight: ['500', '700'], // Load specific font weights
    variable: '--font-raleway', // Optional CSS variable
});
export const metadata: Metadata = {
    title: 'FOSO Entrance Test',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={`${raleway.variable} antialiased`}>
                <NavBar />
                {children}
            </body>
        </html>
    );
}
